const $=s=>document.querySelector(s);let current={address:"",wormholeAddress:"",innerHash:"",legacy:false};
const node=()=>$("#nodeUrl").value.trim(),message=(el,text,error=false)=>{el.textContent=text;el.classList.toggle("error",error)},format=n=>(Number(n)/1e8).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:8});
async function checkNode(){try{const s=await window.korek.status(node());$("#nodeState").textContent=`Online · ${s.networkId} · block ${s.height}`;$("#nodeState").className="online"}catch{$("#nodeState").textContent="Offline";$("#nodeState").className="offline"}}
async function refreshBalance(){try{const regular=await window.korek.balance(node(),"transparent-v1");$("#balance").textContent=format(regular.balance);if(!current.legacy){const wormhole=await window.korek.balance(node(),"wormhole-v1");$("#wormholeBalance").textContent=format(wormhole.balance)}}catch(e){message($("#sendMessage"),e.message,true)}}
function unlocked(result){if(result.canceled)return;current=result;$("#address").textContent=result.address;$("#wormholeAddress").textContent=result.wormholeAddress||"Unavailable for legacy wallet";$("#innerHash").textContent=result.innerHash||"Create or restore a v0.2 wallet";$("#sendScheme").querySelector('[value="wormhole-v1"]').disabled=result.legacy;$("#locked").hidden=true;$("#unlocked").hidden=false;$("#password").value="";$("#mnemonic").value="";if(result.recoveryPhrase){$("#recoveryPhrase").textContent=result.recoveryPhrase;$("#recoveryPhrase").hidden=false;message($("#lockedMessage"),"Write down the 24-word phrase before continuing.")}refreshBalance()}
$("#createWallet").onclick=async()=>{try{message($("#lockedMessage"),"Choose where to save the encrypted wallet…");unlocked(await window.korek.create($("#password").value))}catch(e){message($("#lockedMessage"),e.message,true)}};
$("#restoreWallet").onclick=async()=>{try{message($("#lockedMessage"),"Choose where to save the restored wallet…");unlocked(await window.korek.restore({password:$("#password").value,mnemonic:$("#mnemonic").value}))}catch(e){message($("#lockedMessage"),e.message,true)}};
$("#openWallet").onclick=async()=>{try{message($("#lockedMessage"),"Choose your wallet file…");unlocked(await window.korek.open($("#password").value))}catch(e){message($("#lockedMessage"),e.message,true)}};
$("#refresh").onclick=refreshBalance;$("#copy").onclick=()=>navigator.clipboard.writeText(current.address);$("#copyWormhole").onclick=()=>navigator.clipboard.writeText(current.wormholeAddress);$("#copyInnerHash").onclick=()=>navigator.clipboard.writeText(current.innerHash);
$("#faucet").onclick=async()=>{const button=$("#faucet");button.disabled=true;try{const claim=await window.korek.faucet(node());message($("#faucetMessage"),`Received ${format(claim.amount)} test KRK`);await refreshBalance()}catch(e){message($("#faucetMessage"),e.message,true)}finally{button.disabled=false}};
$("#send").onclick=async()=>{const button=$("#send");button.disabled=true;try{const tx=await window.korek.send({base:node(),to:$("#recipient").value.trim(),amount:$("#amount").value.trim(),scheme:$("#sendScheme").value});message($("#sendMessage"),`Confirmed in ${tx.confirmationTimeMs} ms · Block #${tx.blockHeight}\n${tx.id}`);$("#amount").value="";await refreshBalance()}catch(e){message($("#sendMessage"),e.message,true)}finally{button.disabled=false}};
$("#revealPhrase").onclick=async()=>{try{$("#recoveryPhrase").textContent=await window.korek.recovery();$("#recoveryPhrase").hidden=false}catch(e){message($("#sendMessage"),e.message,true)}};
$("#lock").onclick=async()=>{await window.korek.lock();current={address:"",wormholeAddress:"",innerHash:"",legacy:false};$("#recoveryPhrase").textContent="";$("#recoveryPhrase").hidden=true;$("#unlocked").hidden=true;$("#locked").hidden=false};
document.querySelectorAll(".nav").forEach(button=>button.onclick=()=>{document.querySelectorAll(".nav").forEach(x=>x.classList.toggle("active",x===button));document.querySelectorAll(".page").forEach(page=>page.hidden=page.dataset.page!==button.dataset.page)});$("#nodeUrl").onchange=checkNode;checkNode();setInterval(checkNode,5000);
