const $=(selector)=>document.querySelector(selector); let currentAddress="";
const node=()=>$("#nodeUrl").value.trim(); const message=(el,text,error=false)=>{el.textContent=text;el.classList.toggle("error",error)};
async function checkNode(){try{const s=await window.korek.status(node());$("#nodeState").textContent=`Online · block ${s.height}`;$("#nodeState").className="online"}catch{$("#nodeState").textContent="Offline";$("#nodeState").className="offline"}}
async function refreshBalance(){try{const r=await window.korek.balance(node());$("#balance").textContent=(Number(r.balance)/1e8).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:8})}catch(e){message($("#sendMessage"),e.message,true)}}
function unlocked(result){if(result.canceled)return;currentAddress=result.address;$("#address").textContent=result.address;$("#locked").hidden=true;$("#unlocked").hidden=false;$("#password").value="";refreshBalance()}
$("#createWallet").onclick=async()=>{try{message($("#lockedMessage"),"Choose where to save the encrypted wallet…");unlocked(await window.korek.create($("#password").value));message($("#lockedMessage"),"")}catch(e){message($("#lockedMessage"),e.message,true)}};
$("#openWallet").onclick=async()=>{try{message($("#lockedMessage"),"Choose your wallet file…");unlocked(await window.korek.open($("#password").value));message($("#lockedMessage"),"")}catch(e){message($("#lockedMessage"),e.message,true)}};
$("#refresh").onclick=refreshBalance;$("#copy").onclick=()=>navigator.clipboard.writeText(currentAddress);
$("#faucet").onclick=async()=>{const button=$("#faucet");button.disabled=true;try{const claim=await window.korek.faucet(node());message($("#faucetMessage"),`Received ${Number(claim.amount)/1e8} test KRK`);await refreshBalance()}catch(e){message($("#faucetMessage"),e.message,true)}finally{button.disabled=false}};
$("#send").onclick=async()=>{const button=$("#send");button.disabled=true;try{const tx=await window.korek.send({base:node(),to:$("#recipient").value.trim(),amount:$("#amount").value.trim()});const result=tx.status==="confirmed"?`Confirmed in ${tx.confirmationTimeMs} ms · Block #${tx.blockHeight}`:"Transaction submitted";message($("#sendMessage"),`${result}\n${tx.id}`);$("#amount").value="";await refreshBalance()}catch(e){message($("#sendMessage"),e.message,true)}finally{button.disabled=false}};
$("#lock").onclick=async()=>{await window.korek.lock();currentAddress="";$("#unlocked").hidden=true;$("#locked").hidden=false};
document.querySelectorAll(".nav").forEach(button=>button.onclick=()=>{document.querySelectorAll(".nav").forEach(x=>x.classList.toggle("active",x===button));document.querySelectorAll(".page").forEach(page=>page.hidden=page.dataset.page!==button.dataset.page)});
$("#nodeUrl").onchange=checkNode;checkNode();setInterval(checkNode,5000);
